### ISSUE TITLE
Reporte practica

### ISSUE THREAD

**Issue by Azucena-Tejeda** [SistemasTecTlaxiaco/practica-architect-Azucena-Tejeda#1]
[PRACTICA ARCHITECT Azucena Lopez Tejeda.pdf](https://github.com/SistemasTecTlaxiaco/practica-architect-Azucena-Tejeda/files/7155712/PRACTICA.ARCHITECT.Azucena.Lopez.Tejeda.pdf)

**Comment by IsraelNicolas61** [comment]
¡Buen trabajo!
Calificación 20/20 puntos

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
